# 是否开启调试模式
Debug: true

# Redis配置
Redis:
  Network: "tcp"
  Server: "127.0.0.1"
  Port: 6379
  Pass: ""
  Dbname: 0

# 数据库配置
Database:
  Drive: "mysql"
  User: "root"
  Pass: "root"
  Dbname: "shop"
  Network: "tcp"
  Server: "127.0.0.1"
  Port: 3306

# 日志配置
Logs:
  OutputPaths:
    - "stdout"